function cruiseData = csv2table(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   CRUISEDATA = IMPORTFILE(FILENAME) Reads data from text file FILENAME
%   for the default selection.
%
%   CRUISEDATA = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from
%   rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   cruiseData = importfile('cruiseData.csv', 1, 1313);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2020/06/07 20:00:57

%% Initialize variables.
delimiter = ' ';
if nargin<=2
    startRow = 1;
    endRow = inf;
end

%% Format for each line of text:
%   column1: categorical (%C)
%	column2: double (%f)
%   column3: categorical (%C)
%	column4: double (%f)
%   column5: categorical (%C)
%	column6: double (%f)
%   column7: categorical (%C)
%	column8: double (%f)
%   column9: categorical (%C)
%	column10: double (%f)
%   column11: categorical (%C)
%	column12: double (%f)
%   column13: categorical (%C)
%	column14: double (%f)
%   column15: categorical (%C)
%	column16: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%C%f%C%f%C%f%C%f%C%f%C%f%C%f%C%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
cruiseData = table(dataArray{1:end-1}, 'VariableNames', {'Position_x','VarName2','Position_y','VarName4','Theta','VarName6','Linear_Velocity','VarName8','Angular_Velocity','VarName10','Time','e09','Theta_Ref','VarName14','V_ref','VarName16'});

